import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { cx } from "@/components/utils/cx";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "light-mode dark:dark-mode bg-primary antialiased")}>
                <Theme>{children}</Theme>
            </body>
        </html>
    );
}
